MvcCDISCS/Models/DBModels/career.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MvcCDISCS.Models
{
    /// <summary>
    /// career
    /// </summary>
    public class career
    {
        public int Id { get; set; }
        [Display(Name="招聘标题")]
        [Required(ErrorMessage = "不能为空")]
        public string Title { get; set; }
        [Display(Name = "发布时间")]
        public DateTime CreateTime { get; set; }
        [Display(Name = "过期时间")]
        public DateTime ExpirationTime { get; set; }
        [Display(Name = "招聘要求")]
        [Required(ErrorMessage = "不能为空")]
        public string Content { get; set; }
        [Display(Name = "其他信息")]
        public string Memo { get; set; }
        [Display(Name = "是否显示")]
        public bool IsShow { get; set; }
    }
}

MvcCDISCS/Controllers/CareerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCDISCS.Models;
using System.Data.Entity;
using PagedList;

namespace MvcCDISCS.Controllers
{
    [Authorize]
    public class CareerController : Controller
    {
        CompanyContext db = new CompanyContext();
        //
        // GET: /Career/

        public ActionResult Index(int page = 1)
        {
            IPagedList<career> careers = db.career.OrderByDescending(o => o.CreateTime).ToPagedList(page, 10);
            return View(careers);
        }

        //
        // GET: /Career/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Career/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Career/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(career career)
        {
            try
            {
                career.CreateTime = DateTime.Now;
                if (TryUpdateModel(career))
                {
                    db.career.Add(career);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(career);
            }
            catch
            {
                return HttpNotFound();
            }
        }

        //
        // GET: /Career/Edit/5

        public ActionResult Edit(int id)
        {
            career career = db.career.Find(id);
            if (career == null)
            {
                return HttpNotFound();
            }
            return View(career);
        }

        //
        // POST: /Career/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(career career)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(career).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(career);
            }
            catch
            {
                return HttpNotFound();
            }
        }

        //
        // GET: /Career/Delete/5

        public ActionResult Delete(int id)
        {
            career career = db.career.Find(id);
            if (career == null)
            {
                return HttpNotFound();
            }
            return View(career);
        }

        //
        // POST: /Career/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                career career = db.career.Find(id);
                if (career == null)
                {
                    return HttpNotFound();
                }
                db.career.Remove(career);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcCDISCS/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCDISCS.Models;

namespace MvcCDISCS.Controllers
{
    [Authorize]
    public class FeedbackController : Controller
    {
        CompanyContext db = new CompanyContext();
        //
        // GET: /Feedback/

        public ActionResult Index()
        {
            List<feedback> fbs = db.feedback.OrderByDescending(o => o.FeedbackTime).ToList();
            return View(fbs);
        }

        //
        // GET: /Feedback/Details/5

        public ActionResult Details(int id)
        {
            feedback fb = db.feedback.Find(id);
            if (fb == null)
            {
                return HttpNotFound();
            }
            return View(fb);
        }


        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Feedback/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Feedback/Delete/5

        public ActionResult Delete(int id = 0)
        {
            feedback fb = db.feedback.Find(id);
            if (fb == null)
            {
                return HttpNotFound();
            }
            return View(fb);
        }

        //
        // POST: /Feedback/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                feedback fb = db.feedback.Find(id);
                if (ModelState.IsValid)
                {
                    db.feedback.Remove(fb);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(fb);
            }
            catch
            {
                return HttpNotFound();
            }
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcCDISCS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCDISCS.Models;
using System.Threading;

using PagedList;
using System.Data.Entity;

namespace MvcCDISCS.Controllers
{
    public class HomeController : Controller
    {
        CompanyContext db = new CompanyContext();
        //
        // GET: /Home/

        public ActionResult Index()
        {
            HomeIndex hi = new HomeIndex();
            //get the pagetitle
            hi.PageTitle = db.basicinfo.Find(1).CompanyName;
            //get the slide list
            hi.Slides = db.flash.OrderBy(o => o.Priority).ToList();
            //get notice slide list
            hi.Notices = db.notice.Where(o => o.IsShow == true).OrderBy(o => o.Priority).ToList();
            //get productcategories,5 in count
            hi.ProductCategories = db.productcategory.OrderBy(o => o.Priority).Take(5).ToList();
            //get the introduction
            hi.Introduction = db.morebasicinfo.Where(o => o.Id == 1).Single().ItemContent;
            return View(hi);
        }

        /// <summary>
        /// About
        /// </summary>
        /// <returns></returns>
        public ActionResult About(int id = 0)
        {
            if (id < 1 || id > 10)
            {
                return HttpNotFound();
            }
            morebasicinfo mbc = db.morebasicinfo.Find(id);
            return View(mbc);
        }
        /// <summary>
        /// ProductCategory
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ProductCategory(int id = 0, int page = 1)
        {
            if (id == 0)
            {
                return HttpNotFound();
            }
            ProductCategoryPage pcp = new ProductCategoryPage();
            //分页的实现
            pcp.pc = db.productcategory.Include("Products").Where(o => o.CategoryId == id).Single();
            pcp.products = pcp.pc.Products.ToPagedList(page, 9);
            //清空pc.Products
            pcp.pc.Products = null;
            return View(pcp);
        }

        /// <summary>
        /// 转到搜索页面
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchPage()
        {
            return View();
        }
        /// <summary>
        /// search product as required  for ajax use
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchProduct(string query, int page = 1)
        {
            ViewBag.QueryString = query;
            //如果查询字符串为null或者空，返回产品类别首页
            if (string.IsNullOrEmpty(query))
            {
                return Content("请输入关键词后再查询");
            }
            //TODO:模拟网络延迟
            Thread.Sleep(1500);
            List<product> products = db.product.Include("Category").Where(o => o.ProductName.Contains(query)).OrderBy(o => o.ProductId).ToList();
            return PartialView(products);
        }

        /// <summary>
        /// Product
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Product(int id = 0)
        {
            product p = db.product.Find(id);
            if (p==null)
            {
                return HttpNotFound();
            }
            //read account +1
            p.ReadCount++;
            db.Entry(p).State = EntityState.Modified;
            db.SaveChanges();

            return View(p);
        }
        /// <summary>
        /// Feedback
        /// </summary>
        /// <returns></returns>
        public ActionResult Feedback()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Feedback(feedback fb)
        {
            if (fb == null)
            {
                return HttpNotFound();
            }
            fb.FeedbackTime = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.feedback.Add(fb);
                db.SaveChanges();
                return RedirectToAction("FeedbackSuccess", "Home");
            }
            return View(fb);
        }

        /// <summary>
        /// FeedbackSuccess
        /// </summary>
        /// <returns></returns>
        public ActionResult FeedbackSuccess()
        {
            return View();
        }
        /// <summary>
        /// Service
        /// </summary>
        /// <returns></returns>
        public ActionResult Service()
        {
            List<service> ss = db.service.ToList();
            return View(ss);
        }



        /// <summary>
        /// Contact
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            return View();
        }

        /// <summary>
        /// Career
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult Career(int page = 1)
        {
            //只显示显示标示为true且没有过期的招聘信息
            IPagedList<career> careers = db.career.Where(o => o.IsShow == true&&o.ExpirationTime>DateTime.Now).OrderByDescending(o => o.CreateTime).ToPagedList(page, 10);
            return View(careers);
        }
        public ActionResult CareerDetails(int id)
        {
            career career = db.career.Find(id);
            if (career==null)
            {
                return HttpNotFound();
            }
            return View(career);
        }



        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcCDISCS/Controllers/PVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCDISCS.Models;

namespace MvcCDISCS.Controllers
{
    public class PVController : Controller
    {
        /// <summary>
        ///后面要 给下面这些部分视图添加缓存
        /// </summary>



        CompanyContext db = new CompanyContext();
        /// <summary>
        /// GetContact PartialView
        /// </summary>
        /// <returns></returns>
        [OutputCache(Duration = 600, VaryByParam = "id")]
        public ActionResult GetContact(string show = "no")
        {
            Response.Cache.SetOmitVaryStar(true);

            basicinfo bi = db.basicinfo.Single();
            ViewBag.Show = show;
            return PartialView(bi);
        }

        /// <summary>
        /// GetFriendLink
        /// </summary>
        /// <returns></returns>
        [OutputCache(Duration = 600, VaryByParam = "id")]
        public ActionResult GetFriendLink()
        {
            Response.Cache.SetOmitVaryStar(true);

            ViewBag.FriendLinkList = new SelectList(db.friendlink, "SiteUrl", "SiteName");
            return PartialView();
        }
        /// <summary>
        /// GetProductCategoryMenu
        /// </summary>
        /// <returns></returns>
        [OutputCache(Duration = 600, VaryByParam = "id")]
        public ActionResult GetProductCategoryMenu()
        {
            Response.Cache.SetOmitVaryStar(true);

            List<productcategory> pc = db.productcategory.OrderBy(o => o.Priority).ToList();
            return PartialView(pc);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcCDISCS/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcCDISCS.Models;
using System.Data.Entity;

namespace MvcCDISCS.Controllers
{
    [Authorize]
    public class ProductCategoryController : Controller
    {
        CompanyContext db = new CompanyContext();
        //
        // GET: /ProductCategory/

        public ActionResult Index()
        {
            List<productcategory> pclist = db.productcategory.ToList();
            return View(pclist);
        }

        //
        // GET: /ProductCategory/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /ProductCategory/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ProductCategory/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(productcategory pc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.productcategory.Add(pc);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(pc);
            }
            catch
            {
                return HttpNotFound();
            }
        }

        //
        // GET: /ProductCategory/Edit/5

        public ActionResult Edit(int id)
        {
            productcategory pc = db.productcategory.Find(id);
            if (pc == null)
            {
                return HttpNotFound();
            }
            return View(pc);
        }

        //
        // POST: /ProductCategory/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(productcategory pc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(pc).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View(pc);
            }
            catch
            {
                return HttpNotFound();
            }
        }

        //
        // GET: /ProductCategory/Delete/5

        public ActionResult Delete(int id)
        {
            productcategory pc = db.productcategory.Find(id);
            if (pc == null)
            {
                return HttpNotFound();
            }
            return View(pc);
        }

        //
        // POST: /ProductCategory/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                productcategory pc = db.productcategory.Find(id);
                if (pc == null)
                {
                    return HttpNotFound();
                }
                db.productcategory.Remove(pc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return HttpNotFound();
            }
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcCDISCS/Views/Home/About.cshtml
@model MvcCDISCS.Models.morebasicinfo
@{
    ViewBag.PageTitle = Model.ItemName;
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}
@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">关于我们</h3>
        <ul>
            <li><a href="~/Home/About/1">公司简介</a></li>
            <li><a href="~/Home/About/2">公司管理</a></li>
            <li><a href="~/Home/About/3">发展历程</a></li>
            <li><a href="~/Home/About/4">荣誉资质</a></li>
            <li><a href="~/Home/About/5">公司客户</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">招聘信息</h3>
        <ul>
            <li><a href="~/Home/Career">招聘信息</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}
@section rightpart{
    <div class="htmlcontent">
        @Html.Raw(Model.ItemContent)
    </div>
}

MvcCDISCS/Views/Home/Career.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<MvcCDISCS.Models.career>

@{
    ViewBag.PageTitle = "招聘信息";
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}
@section cssmore2{
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
}
@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">关于我们</h3>
        <ul>
            <li><a href="~/Home/About/1">公司简介</a></li>
            <li><a href="~/Home/About/2">公司管理</a></li>
            <li><a href="~/Home/About/3">发展历程</a></li>
            <li><a href="~/Home/About/4">荣誉资质</a></li>
            <li><a href="~/Home/About/5">公司客户</a></li>
            <li><a href="~/Home/Career">招聘信息</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}
@section rightpart{
    <div>
        @if (Model.Count > 0)
        {
            foreach (var item in Model)
            {
                <p class="listp"><a href="~/Home/CareerDetails/@(item.Id)">@Html.DisplayFor(o => item.Title) [@(item.CreateTime)]</a></p>
            }
            @Html.PagedListPager(Model, page => Url.Action("Career", new { page }))
        }
        else
        {
            <p>抱歉，暂时没有招聘信息~</p>
        }
    </div>
}

MvcCDISCS/Views/Home/CareerDetails.cshtml
@model MvcCDISCS.Models.career
@{
    ViewBag.PageTitle = "招聘信息详情";
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}
@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">关于我们</h3>
        <ul>
            <li><a href="~/Home/About/1">公司简介</a></li>
            <li><a href="~/Home/About/2">公司管理</a></li>
            <li><a href="~/Home/About/3">发展历程</a></li>
            <li><a href="~/Home/About/4">荣誉资质</a></li>
            <li><a href="~/Home/About/5">公司客户</a></li>
            <li><a href="~/Home/Career">招聘信息</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">招聘信息</h3>
        <ul>
            <li><a href="~/Home/Career">招聘信息</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}
@section rightpart{
    <div class="htmlcontent">
        <table class="details-table">
            <tr>
                <td class="tdhead">@Html.DisplayNameFor(o => o.Title)</td>
                <td class="tdcotent">@Html.DisplayFor(o => o.Title)</td>
            </tr>
            <tr>
                <td class="tdhead">@Html.DisplayNameFor(o => o.CreateTime)</td>
                <td class="tdcotent">@Html.DisplayFor(o => o.CreateTime)</td>
            </tr>
            <tr>
                <td class="tdhead">@Html.DisplayNameFor(o => o.ExpirationTime)</td>
                <td class="tdcotent">@Html.DisplayFor(o => o.ExpirationTime)</td>
            </tr>
            <tr>
                <td class="tdhead">@Html.DisplayNameFor(o => o.Content)</td>
                <td class="tdcotent">@Html.Raw(Model.Content)</td>
            </tr>
            <tr>
                <td class="tdhead">@Html.DisplayNameFor(o => o.Memo)</td>
                <td class="tdcotent">@Html.Raw(Model.Memo)</td>
            </tr>
        </table>
    </div>
}

MvcCDISCS/Views/Home/Contact.cshtml
@{
    ViewBag.PageTitle = "联系我们";
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}
@section cssmore2{
    
}
@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}
@section rightpart{
    <div id="contactcontent" class="htmlcontent">
        @Html.Action("GetContact", "PV", new { show = "no" })
    </div>
    <div id="contactmapcontent">
        <p>下面是我公司在地图上的具体位置:</p>
        <img src="~/Images/cdiscs/map.png" alt="helloworld" />
    </div>
}

MvcCDISCS/Views/Home/FeedbackSuccess.cshtml
@{
    ViewBag.PageTitle = "留言成功";
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}

@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">产品类别</h3>
        <ul>
            @Html.Action("GetProductCategoryMenu", "PV")
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
        </ul>
    </div>
}

@section rightpart{
    <div class="htmlcontent">
    <p>谢谢您的留言，我们会尽快给你反馈~</p>
</div>
}

MvcCDISCS/Views/Home/GetContact.cshtml
@model MvcCDISCS.Models.basicinfo

<li>
    @Html.DisplayFor(o=>o.CompanyName)
</li>
<li>
    @Html.DisplayNameFor(o => o.Contact):
    @Html.DisplayFor(o => o.Contact)
</li>
<li>
    @Html.DisplayNameFor(o => o.Phone):
    @Html.DisplayFor(o => o.Phone)
</li>
<li>
    @Html.DisplayNameFor(o => o.Fax):
    @Html.DisplayFor(o => o.Fax)
</li>
<li>
    @Html.DisplayNameFor(o => o.Email):
    @Html.DisplayFor(o => o.Email)
</li>
<li>
    @Html.DisplayNameFor(o => o.PostCode):
    @Html.DisplayFor(o => o.PostCode)
</li>
<li>
    @Html.DisplayNameFor(o => o.Address):
    @Html.DisplayFor(o => o.Address)
</li>

MvcCDISCS/Views/Home/Product.cshtml
@model MvcCDISCS.Models.product
@{
    ViewBag.PageTitle = Model.ProductName;
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}

@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">产品搜索</h3>
        <ul>
            <li><a href="~/Home/SearchPage">产品搜索</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">产品类别</h3>
        <ul>
            @Html.Action("GetProductCategoryMenu", "PV")
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}
@section rightpart{
    <p class="publishday">发布日期:@Model.PublishTime  阅读次数:@Model.ReadCount</p>
    <div id="productdetailscontent" class="htmlcontent">
        @Html.Raw(Model.Content)
    </div>
}

MvcCDISCS/Views/Home/ProductCategory.cshtml
@using PagedList.Mvc
@model MvcCDISCS.Models.ProductCategoryPage
@{
    ViewBag.PageTitle = Model.pc.CategoryName;
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}
@section cssmore2{
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/form.css" rel="stylesheet" type="text/css" />
}
@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">产品搜索</h3>
        <ul>
            <li><a href="~/Home/SearchPage">产品搜索</a></li>
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">产品类别</h3>
        <ul>
            @Html.Action("GetProductCategoryMenu", "PV")
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}

@section rightpart{
    <div id="topcontent">
        <img src="~/Images/category/@(Model.pc.Photo).jpg" alt="@Model.pc.CategoryName" id="titleimg" class="smallphotobg" />
        <p>@Html.Raw(Model.pc.Memo)</p>
    </div>
    <div id="productlist">
        <!--display the products under the category list-->
        @if (Model.products.Count > 0)
        {
            foreach (var item in Model.products)
            {
                <a href="~/Home/Product/@item.ProductId" class="smallphotobg">
                    <img src="~/Images/product/@(item.Photo).jpg" alt="@item.Photo" />
                    <p>@item.ProductName</p>
                </a>
            }
        }
        else
        {
            <div>抱歉，该分类下暂时没有添加产品，请等待</div>
        }
    </div>
    <!--分页内容-->
    @Html.PagedListPager(Model.products, page => Url.Action("ProductCategory", new { id = Model.pc.CategoryId, page }))
}

MvcCDISCS/Views/Home/SearchPage.cshtml
@{
    ViewBag.PageTitle = "产品搜索";
    Layout = "~/Views/Shared/_FrontEndContent.cshtml";
}

@section cssmore2{
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/form.css" rel="stylesheet" type="text/css" />
    <script>
        function searchFailed() {
            $("#productcategorycontent").html("对不起，搜索出现错误~")
        }
    </script>
}
@section leftpart{
    <div class="partmenu">
        <h3 class="titlebar">产品类别</h3>
        <ul>
            @Html.Action("GetProductCategoryMenu", "PV")
        </ul>
    </div>
    <div class="partmenu">
        <h3 class="titlebar">联系我们</h3>
        <ul>
            <li><a href="~/Home/Contact">联系方式</a></li>
            <li><a href="~/Home/Feedback">网上留言</a></li>
        </ul>
    </div>
}

@section rightpart{
    <!--searcharea-->
    <div id="searcharea" class="roundborder">

        <!--ajax form-->
        @using (Ajax.BeginForm("SearchProduct", "Home", new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET",
            OnFailure = "searchFailed",
            LoadingElementId = "ajax-loader",
            UpdateTargetId = "productcategorycontent"
        }))
        {
            <input type="text" value="" placeholder="可以在此输入你要搜索的产品关键词进行搜索" name="query" /><input type="submit" value="搜索" class="btnsearch" />
            <span id="ajax-loader" style="display:none;">正在搜索，请稍后……</span>
        }
    </div>
    <div id="productcategorycontent">

    </div>
}